# Generated by Django 5.0 on 2025-10-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='disponible',
        ),
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('revision', 'En revisión')], default='disponible', max_length=20),
        ),
    ]
