# Generated by Django 5.0 on 2025-10-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='numero_socio',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
