# Generated by Django 5.0 on 2025-10-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multa',
            name='prestamo',
        ),
        migrations.AddField(
            model_name='multa',
            name='libro_titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
